### ISSUE TITLE
Allow enforcement of custom naming conventions

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/regal#19]
While we'll want to enforce snake_case naming of rules and vars by default, it'd be nice if we provided an optional rule to enforce custom naming conventions. This could be provided in the form of a regex, that would be checked against all rule names and vars.

**Comment by anderseknert** [comment]
As for what this would look like, I think something like this would make for a good option. Configuration file would look something like this:

```yaml
rules:
  custom:
    naming:
      - target: rule
        # allow only "private" rules, i.e. those starting with underscore,
        # or rules named "deny" or "allow"
        pattern: '^_[a-z]+$|^deny$|^allow$'
      - target: package
        # package names must start with "acmecorp" or "system"
        pattern: '^acmecorp|^system'
```

Possible targets would be:
- rule
- function
- package
- var

Any others?

Another open question is whether there's a case for allowing ignores on files for certain patterns? Or if the existing rule-level ignores are good enough. I think we could start with that, and add a pattern level ignore option only if requested.
